import = ["~/.config/alacritty/themes/gruvbox-material.toml"]

[shell]
program = "/usr/bin/zsh"

[font]
size = 11
normal = { family = "JetBrainsMonoNerdFontMono" }
# normal = { family = "FiraCodeNerdFontMono" }

[window]
opacity = 0.75
blur = true
